# sample meta data fil
# this file must have the header sample_id<tab>fastq_1<tab>fastq_2.  (The second tab and fastq_2 are optional.)
sample_tsv: "sample_fastq_paired.txt"

# library layout
layout: "single"

# aligner choice
aligner_name: "hisat" #'hisat' or 'star'

# rsem choice
run_rsem: "no"

#############################################
#Strandedness settings - these should match #
#############################################
featurecounts_strand: "1" # '1', '0'
rsem_strandedness: "forward" # 'foward', 'none'
picard_strand: "FIRST_READ_TRANSCRIPTION_STRAND" # 'FIRST_READ_TRANSCRIPTION', 'NONE'


#############################################
# miscellaneous settings ####################
#############################################
cutadapt_nextseq_flag: "" # '--nextseq-trim-20'
cutadapt_nextseq_flag: "" # '--nextseq-trim-20'

#############################################
# Input reference fasta and GTF annotation ##
#############################################
reference_fa: "/dartfs/rc/nosnapshots/G/GMBSR_refs/Mmusculus/GRCm39/downloads/GRCm39.primary_assembly.genome.fa"
annotation_gtf: "/dartfs/rc/nosnapshots/G/GMBSR_refs/Mmusculus/GRCm39/downloads/gencode.vM34.annotation.gtf"


#############################################
# Aligner index and picard references #######
# create and specify these or ###############
# run snakemake build_ref rule to create ####
#############################################
aligner_index: '/dartfs/rc/nosnapshots/G/GMBSR_refs/Mmusculus/GRCm39/rna_index/hisat2_index/GRCm39.primary_assembly.genome'
picard_refflat: '/dartfs/rc/nosnapshots/G/GMBSR_refs/Mmusculus/GRCm39/annotation/picard/GRCm39.primary_assembly.genome.refFlat'
picard_rrna_list: '/dartfs/rc/nosnapshots/G/GMBSR_refs/Mmusculus/GRCm39/annotation/picard/GRCm39.primary_assembly.genome.rRNA.interval.list'
rsem_ref_path: '/dartfs/rc/nosnapshots/G/GMBSR_refs/Mmusculus/GRCm39/rna_index/RSEM_index/'

#############################################
# Pipeline scripts ##########################
#############################################
picard_build_script: "scripts/picard_ref_builder.sh"
featurecounts_rscript: "scripts/readcnt_to_rpkmtpm.py"
featurecounts_annscript: "scripts/add_gene_to_ensg.py"
pca_plot_script: "scripts/pca_plotting.py"


#############################################
# Software Paths for use with "--use-conda" #
############################################# 
cutadapt_path: "cutadapt"
fastqc_path: "fastqc"
samtools_path: "samtools"
aligner_path: "hisat2"
picard_path: "picard"
featurecounts_path: "featureCounts"
rsem_calc_exp_path: "rsem-calculate-expression"
rsem_prep_ref_path: "rsem-prepare-reference"
multiqc_path: "multiqc"


############################################# 
# Custom Software Paths #####################
############################################# 
#cutadapt_path: "/dartfs-hpc/rc/home/d/d41294d/.conda/envs/rnaseq1/bin/cutadapt"
#multiqc_path: "/dartfs-hpc/rc/home/d/d41294d/.conda/envs/rnaseq1/bin/multiqc"
#fastqc_path: "/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/misc/sullivan/tools/fastqc/FastQC/fastqc"
#picard_path: "/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/misc/sullivan/tools/picard/picard.jar"
#java_path: "/usr/bin/java"
#samtools_path: "/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/misc/sullivan/tools/samtools/samtools-1.11/samtools"
#featurecounts_path: "/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/misc/sullivan/tools/featurecounts/subread-2.0.1-Linux-x86_64/bin/featureCounts"
#multiqc_path: "/dartfs-hpc/rc/home/d/d41294d/.conda/envs/rnaseq1/bin/multiqc"
#aligner_path: "/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/misc/sullivan/tools/hisat2/hisat2-2.1.0/hisat2"



###~~~~~~ alignment settings ~~~~~~###
#aligner_index: "/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/genomic_references/human/STAR/hg38_index"
###~~~~~~ quant settings ~~~~~~###
#annotation_gtf: "/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/genomic_references/human/ensembl-annotations/Homo_sapiens.GRCh38.97.gtf"


# todo: remove those and generate in build_ref rule
#rsem_ref_path: "sample_ref/RSEM_ref"


#rsem_ref_path: "/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/genomic_references/human/RSEM/txdir/RSEMref"

#picard_rrna_list: "/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/genomic_references/human/CollectRnaSeqMetrics/Homo_sapiens.GRCh38.97.rRNA.interval_list"
#picard_refflat: "/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/genomic_references/human/CollectRnaSeqMetrics/Homo_sapiens.GRCh38.97.refFlat.txt"

#featurecounts_strand: "2" #1 for first read transcription strand, 2 for second.

#rsem_ref_path: "/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/genomic_references/human/RSEM/txdir/RSEMref"
#
##picard_rrna_list: "/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/genomic_references/human/CollectRnaSeqMetrics/Homo_sapiens.GRCh38.97.rRNA.interval_list"
##picard_refflat: "/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/genomic_references/human/CollectRnaSeqMetrics/Homo_sapiens.GRCh38.97.refFlat.txt"
#picard_strand: "SECOND_READ_TRANSCRIPTION_STRAND"

