sample_tsv: "sample_fastq_list_paired.txt"

cutadapt_path: "/dartfs-hpc/rc/home/j/f00331j/.conda/envs/rnaseq/bin/cutadapt"
multiqc_path: "/dartfs-hpc/rc/home/j/f00331j/.conda/envs/rnaseq/bin/multiqc"

fastqc_path: "/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/misc/sullivan/tools/fastqc/FastQC/fastqc"
umi_tools_path: "/dartfs-hpc/rc/home/j/f00331j/.conda/envs/umi-tools/bin/umi_tools"

#java_path: "/opt/java/jdk1.8.0_66/bin/java"
java_path: "/dartfs-hpc/rc/home/j/f00331j/.conda/pkgs/java-jdk-8.0.92-1/bin/java"

samtools_path: "/dartfs-hpc/rc/home/j/f00331j/.conda/envs/rnaseq/bin/samtools"


picard_path: "/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/misc/sullivan/tools/picard/picard.jar"
picard_refflat: "/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/genomic_references/mouse/CollectRnaSeqMetrics/Mus_musculus.GRCm38.97.refFlat.txt"
picard_rrna_list: "/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/genomic_references/mouse/CollectRnaSeqMetrics/Mus_musculus.GRCm38.97.rRNA.interval_list"
picard_strand: "SECOND_READ_TRANSCRIPTION_STRAND"

#samtools_path: "/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/misc/sullivan/tools/samtools/samtools-1.11/samtools"

hisat_path: "/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/misc/sullivan/tools/hisat2/hisat2-2.1.0/hisat2"
hisat_index: "/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/genomic_references/mouse/HISAT2/Mus_musculus.GRCm38.dna.primary_assembly"
annotation_gtf: "/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/genomic_references/mouse/ensembl-annotations/Mus_musculus.GRCm38.97.gtf"




layout: "paired"

aligner_name: "hisat" #'hisat' or 'star'
aligner_path: "/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/misc/sullivan/tools/hisat2/hisat2-2.1.0/hisat2"
aligner_index: "/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/genomic_references/mouse/HISAT2/Mus_musculus.GRCm38.dna.primary_assembly"
#aligner_path: "/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/misc/sullivan/tools/STAR/STAR-2.7.1a/bin/Linux_x86_64/STAR"
#aligner_index: "/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/genomic_references/human/STAR/hg38_index"

#annotation_gtf: "/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/genomic_references/human/ensembl-annotations/Homo_sapiens.GRCh38.97.gtf"


featurecounts_path: "/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/misc/sullivan/tools/featurecounts/subread-2.0.1-Linux-x86_64/bin/featureCounts"
featurecounts_strand: "2" #1 for first read transcription strand, 2 for second.
featurecounts_rscript: "/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/misc/sullivan/tools/featurecounts/subread-2.0.1-Linux-x86_64/bin/fc_to_rpkmtpm.R"
featurecounts_annscript: "/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/misc/sullivan/tools/featurecounts/subread-2.0.1-Linux-x86_64/bin/add_gene_to_ensg.py"

rsem_path: "/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/misc/owen/software/bin"
rsem_ref_path: "/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/genomic_references/human/RSEM/txdir/RSEMref"


trimmomatic_path: "/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/misc/sullivan/tools/trimmomatic/Trimmomatic-0.39/trimmomatic-0.39.jar"
trimmomatic_adapters: "/dartfs-hpc/rc/lab/G/GMBSR_bioinfo/misc/sullivan/tools/trimmomatic/Trimmomatic-0.39/adapters/TruSeq3-PE-2.fa_wpoly.fa"

